# Generated by Django 2.1.5 on 2019-01-23 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='stock_info',
            name='stock_type',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='stock_price',
            name='stock_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Stock_Info'),
        ),
    ]
