# Generated by Django 2.1.5 on 2019-01-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20190126_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='ticker',
            field=models.CharField(default='', max_length=10),
        ),
    ]
