# Generated by Django 2.1.5 on 2019-01-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_stock_ticker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='latest_spread',
            new_name='spread',
        ),
    ]
