# Generated by Django 2.1.5 on 2019-02-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_remove_stock_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='info',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='stock_info',
            name='url',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='stock_info',
            name='volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock_info',
            name='latest_price',
            field=models.FloatField(null=True),
        ),
    ]
